### ISSUE TITLE
Error setMockLocation

### ISSUE THREAD

**Issue by wahyuutomoputra** [Kaique292/react-native-android-mock-location#1]
i used this in expo and got an error

 ERROR  Error: The package 'react-native-android-mock-location' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo Go
, js engine: hermes

**Comment by Kaique292** [comment]
@wahyuutomoputra This is because you are using Expo Go. U have to use Expo Dev Client

**Comment by wahyuutomoputra** [comment]
Thank You
